---
title: "sediment_matter_2017"
author: "Tiff Stephens"
date: "3/20/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(plyr)
library(tidyr)
```



```{r}
# import RAW data
df.matter <- read.csv("/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_DATA/DATA_ARCHIVING/Tiff/Sediment core (deep) [2017]/sediment_core_2017_RAW.csv", stringsAsFactors = FALSE, header = TRUE)
```

```{r}
# calculate dry bulk density (DBD)
df.matter = df.matter %>% 
  mutate(layer_volume_cm3 = pi*((2.5)^2)*layer_thickness_cm, na.rm = TRUE) %>%
  mutate(sed_ww_pre_60C_g = pan_sed_ww_pre_60C_g - pan_weight_g, na.rm = TRUE) %>% # not needed for DBD but a good factor to have for later ww:dw conversions
  mutate(sed_dw_post_60C_g = pan_sed_dw_post_60C_g - pan_weight_g, na.rm = TRUE) %>%
  mutate(dry_bulk_density = sed_dw_post_60C_g / layer_volume_cm3, na.rm = TRUE)


# calculate organic matter (OM)
df.matter = df.matter %>% 
  mutate(sed_dw_pre_450C_g = pan_sed_dw_pre_450C_g - pan_weight_g, na.rm = TRUE) %>%
  mutate(sed_dw_post_450C_g = pan_sed_dw_post_450C_g - pan_weight_g, na.rm = TRUE) %>%
  mutate(organic_dw_g = sed_dw_pre_450C_g - sed_dw_post_450C_g, na.rm = TRUE)
  

# calculate inorganic matter (IM)
df.matter = df.matter %>%   
  mutate(sed_dw_pre_950C_g = crucible_sed_dw_pre_950C_g - crucible_weight_g, na.rm = TRUE) %>%
  mutate(sed_dw_post_950C_g = crucible_sed_dw_post_950C_g - crucible_weight_g, na.rm = TRUE) %>%
  mutate(inorganic_dw_g = sed_dw_pre_950C_g - sed_dw_post_950C_g)


# calculate the depth of each layer using the layer number (each layer was cut at 2 cm but adjusted using the compaction coefficient that was pre-determined prior to slicing the cores)
df.matter = df.matter %>% 
  mutate(layer_depth_cm = (layer_number * 2) - 2, na.rm = TRUE)
```

```{r}
# calculate other important data
df.matter = df.matter %>% 
  mutate(organic_dw_percent = (organic_dw_g / sed_dw_pre_450C_g) * 100, na.rm = TRUE) %>%
  mutate(inorganic_dw_percent = (inorganic_dw_g / sed_dw_pre_950C_g) * 100, na.rm = TRUE) %>%
  mutate(organic_density = organic_dw_g * dry_bulk_density, na.rm = TRUE) %>%
  mutate(inorganic_density = inorganic_dw_g * dry_bulk_density, na.rm = TRUE)

df1 <- aggregate(organic_dw_percent ~ site_name, data = df.matter, mean, na.rm = TRUE)

```

```{r}
colnames(df.matter)

# remove columns that are not useful for archiving
df.matter = df.matter %>% 
  select(-pan_weight_g, -pan_sed_ww_pre_60C_g, -pan_sed_dw_post_60C_g, -pan_sed_dw_pre_450C_g, -pan_sed_dw_post_450C_g, -crucible_weight_g, -crucible_sed_dw_pre_950C_g, -crucible_sed_dw_post_950C_g, -sed_ww_pre_60C_g, -sed_dw_post_60C_g, -sed_dw_pre_450C_g, -sed_dw_post_450C_g, -sed_dw_pre_950C_g, -sed_dw_post_950C_g)
```

```{r}
# print final, cleaned .csv file
write.csv(df.matter, "/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_DATA/DATA_ARCHIVING/Tiff/Sediment core (deep) [2017]/sediment_core_2017_CLEAN.csv", row.names = TRUE)
```


